LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := isee_product.cfg
LOCAL_SRC_FILES := $(MICROTRUST_TEE_VERSION)/teei/$(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/thh/ta
LOCAL_MODULE_CLASS := ETC
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := TAs_list
LOCAL_SRC_FILES := $(MICROTRUST_TEE_VERSION)/teei/$(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/thh/ta
LOCAL_MODULE_CLASS := ETC
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

ifneq ($(strip $(KEYMASTER_VERSION)), 5.0)
include $(CLEAR_VARS)
LOCAL_MODULE := keymaster_server4
LOCAL_SRC_FILES := $(MICROTRUST_TEE_VERSION)/teei/$(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/thh/ta
LOCAL_INSTALLED_MODULE_STEM := c09c9c5daa504b78b0e46eda61556c3a.ta
LOCAL_MODULE_CLASS := ETC
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)
else
include $(CLEAR_VARS)
LOCAL_MODULE := keymint_server
LOCAL_SRC_FILES := $(MICROTRUST_TEE_VERSION)/teei/$(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/thh/ta
LOCAL_INSTALLED_MODULE_STEM := c09c9c5daa504b78b0e46eda61556c3a.ta
LOCAL_MODULE_CLASS := ETC
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)
endif

include $(CLEAR_VARS)
LOCAL_MODULE := gatekeeper_server
LOCAL_SRC_FILES := $(MICROTRUST_TEE_VERSION)/teei/$(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/thh/ta
LOCAL_INSTALLED_MODULE_STEM := c1882f2d885e4e13a8c8e2622461b2fa.ta
LOCAL_MODULE_CLASS := ETC
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := km_key_manager_ta
LOCAL_SRC_FILES := $(MICROTRUST_TEE_VERSION)/teei/$(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/thh/ta
LOCAL_INSTALLED_MODULE_STEM := d91f322ad5a441d5955110eda3272fc0.ta
LOCAL_MODULE_CLASS := ETC
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := isee_model.json
LOCAL_SRC_FILES := $(MICROTRUST_TEE_VERSION)/teei/$(LOCAL_MODULE)
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/thh/ta
LOCAL_INSTALLED_MODULE_STEM := $(LOCAL_MODULE)
LOCAL_MODULE_CLASS := ETC
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := mtk
LOCAL_MULTILIB := 32
include $(BUILD_PREBUILT)

